version: "3.8"

services:
  server:
    build: ./server
    links:
      - "db"
    depends_on:
      - "db"
    environment:
      PORT: '8000'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '3306'
      DATABASE_NAME: 'ticketing-db'
      DATABASE_USER: 'user'
      DATABASE_PASSWORD: 'password'
    ports:
      - "8000:8000"
    expose:
      - "8000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "ticketing-db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ticketing-db:/var/lib/mysql

volumes:
  ticketing-db:
